# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-11 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20190910_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipped',
            field=models.BooleanField(default=False),
        ),
    ]
