# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-09 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShirtSize',
            fields=[
                ('tshirt_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.Tshirt')),
                ('shirt_size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=2)),
            ],
            bases=('shop.tshirt',),
        ),
        migrations.RemoveField(
            model_name='tshirt',
            name='shirt_size',
        ),
    ]
