# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-09 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190709_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shirtsize',
            old_name='shirt_size',
            new_name='size',
        ),
    ]
