# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-09 18:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190709_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shirtsize',
            name='tshirt_ptr',
        ),
        migrations.DeleteModel(
            name='ShirtSize',
        ),
    ]
