# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-09 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190709_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='tshirt',
            name='shirt_size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
    ]
