# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-03 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodOrBad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('align', models.CharField(choices=[('Schad', 'Schadenfreude'), ('FCP', 'Fight Club: Pro')], default='FCP', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Wrestler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthplace', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images')),
                ('description', models.TextField()),
                ('alignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.GoodOrBad')),
                ('titles', models.ManyToManyField(to='roster.Title')),
            ],
        ),
    ]
