# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-03 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='number_of_reigns',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
