# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-03 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0002_title_number_of_reigns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodorbad',
            name='align',
            field=models.CharField(choices=[('Schadenfreude', 'Schadenfreude'), ('FCP', 'Fight Club: Pro')], default='FCP', max_length=32),
        ),
    ]
