# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-05 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0004_auto_20190905_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='wrestler',
            name='socials',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='roster.SocialMedia'),
            preserve_default=False,
        ),
    ]
