# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-05 14:09
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0006_socialmedia_socialmedias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wrestler',
            name='socials',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Twitter', 'Twitter'), ('Instagram', 'Instagram'), ('NoSocial', 'NoSocial')], default='NoSocial', max_length=30),
        ),
        migrations.DeleteModel(
            name='SocialMedia',
        ),
    ]
