# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-05 14:11
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0007_auto_20190905_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wrestler',
            name='socials',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Twitter', 'Twitter'), ('Instagram', 'Instagram'), ('NoSocial', 'NoSocial')], default='NoSocial', max_length=30),
        ),
    ]
