# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-05 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0010_auto_20190905_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wrestler',
            name='socials',
        ),
    ]
