# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-11 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_trainingform_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingform',
            name='contacted',
            field=models.BooleanField(default=False),
        ),
    ]
