# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-19 22:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_trainingform_contacted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingform',
            name='phone_number',
        ),
    ]
